##
## This is part of Japanese translation version for Hugo Documantation.
##

bases = \
	Abs.md       \
	Acos.md      \
	Add.md       \
	Asin.md      \
	Atan.md      \
	Atan2.md     \
	Ceil.md      \
	Cos.md       \
	Counter.md   \
	Div.md       \
	Floor.md     \
	Log.md       \
	Max.md       \
	Min.md       \
	Mod.md       \
	ModBool.md   \
	Mul.md       \
	Pi.md        \
	Pow.md       \
	Product.md   \
	Rand.md      \
	Round.md     \
	Sin.md       \
	Sqrt.md      \
	Sub.md       \
	Sum.md       \
	Tan.md       \
	ToDegrees.md \
	ToRadians.md \
	_index.md

include $(top_srcdir)/build-aux/common.mk
include $(top_srcdir)/build-aux/content.mk
