##
## This is part of Japanese translation version for Hugo Documantation.
##

SUBDIRS = _common types

bases = \
	404.md                   \
	_index.md                \
	base.md                  \
	content-view.md          \
	embedded.md              \
	home.md                  \
	introduction.md          \
	lookup-order.md          \
	menu.md                  \
	output-formats.md        \
	pagination.md            \
	partial.md               \
	robots.md                \
	rss.md                   \
	section.md               \
	shortcode.md             \
	single.md                \
	sitemap.md               \
	taxonomy.md              \
	term.md

include $(top_srcdir)/build-aux/common.mk
include $(top_srcdir)/build-aux/content.mk
